# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/adamj/QtProjects/CodeWizard

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/adamj/QtProjects/CodeWizard

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adamj/QtProjects/CodeWizard/CMakeFiles /home/adamj/QtProjects/CodeWizard//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/adamj/QtProjects/CodeWizard/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tree-sitter-cpp

# Build rule for target.
tree-sitter-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-cpp
.PHONY : tree-sitter-cpp

# fast build rule for target.
tree-sitter-cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-cpp.dir/build.make CMakeFiles/tree-sitter-cpp.dir/build
.PHONY : tree-sitter-cpp/fast

#=============================================================================
# Target rules for targets named tree-sitter-c-sharp

# Build rule for target.
tree-sitter-c-sharp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-c-sharp
.PHONY : tree-sitter-c-sharp

# fast build rule for target.
tree-sitter-c-sharp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c-sharp.dir/build.make CMakeFiles/tree-sitter-c-sharp.dir/build
.PHONY : tree-sitter-c-sharp/fast

#=============================================================================
# Target rules for targets named tree-sitter-python

# Build rule for target.
tree-sitter-python: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-python
.PHONY : tree-sitter-python

# fast build rule for target.
tree-sitter-python/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-python.dir/build.make CMakeFiles/tree-sitter-python.dir/build
.PHONY : tree-sitter-python/fast

#=============================================================================
# Target rules for targets named tree-sitter-rust

# Build rule for target.
tree-sitter-rust: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-rust
.PHONY : tree-sitter-rust

# fast build rule for target.
tree-sitter-rust/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-rust.dir/build.make CMakeFiles/tree-sitter-rust.dir/build
.PHONY : tree-sitter-rust/fast

#=============================================================================
# Target rules for targets named tree-sitter-javascript

# Build rule for target.
tree-sitter-javascript: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-javascript
.PHONY : tree-sitter-javascript

# fast build rule for target.
tree-sitter-javascript/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-javascript.dir/build.make CMakeFiles/tree-sitter-javascript.dir/build
.PHONY : tree-sitter-javascript/fast

#=============================================================================
# Target rules for targets named tree-sitter-typescript

# Build rule for target.
tree-sitter-typescript: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-typescript
.PHONY : tree-sitter-typescript

# fast build rule for target.
tree-sitter-typescript/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-typescript.dir/build.make CMakeFiles/tree-sitter-typescript.dir/build
.PHONY : tree-sitter-typescript/fast

#=============================================================================
# Target rules for targets named tree-sitter-html

# Build rule for target.
tree-sitter-html: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-html
.PHONY : tree-sitter-html

# fast build rule for target.
tree-sitter-html/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-html.dir/build.make CMakeFiles/tree-sitter-html.dir/build
.PHONY : tree-sitter-html/fast

#=============================================================================
# Target rules for targets named tree-sitter-lua

# Build rule for target.
tree-sitter-lua: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-lua
.PHONY : tree-sitter-lua

# fast build rule for target.
tree-sitter-lua/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-lua.dir/build.make CMakeFiles/tree-sitter-lua.dir/build
.PHONY : tree-sitter-lua/fast

#=============================================================================
# Target rules for targets named tree-sitter-glsl

# Build rule for target.
tree-sitter-glsl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-glsl
.PHONY : tree-sitter-glsl

# fast build rule for target.
tree-sitter-glsl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-glsl.dir/build.make CMakeFiles/tree-sitter-glsl.dir/build
.PHONY : tree-sitter-glsl/fast

#=============================================================================
# Target rules for targets named tree-sitter-wgsl

# Build rule for target.
tree-sitter-wgsl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-wgsl
.PHONY : tree-sitter-wgsl

# fast build rule for target.
tree-sitter-wgsl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-wgsl.dir/build.make CMakeFiles/tree-sitter-wgsl.dir/build
.PHONY : tree-sitter-wgsl/fast

#=============================================================================
# Target rules for targets named tree-sitter-go

# Build rule for target.
tree-sitter-go: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-go
.PHONY : tree-sitter-go

# fast build rule for target.
tree-sitter-go/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-go.dir/build.make CMakeFiles/tree-sitter-go.dir/build
.PHONY : tree-sitter-go/fast

#=============================================================================
# Target rules for targets named tree-sitter-java

# Build rule for target.
tree-sitter-java: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-java
.PHONY : tree-sitter-java

# fast build rule for target.
tree-sitter-java/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-java.dir/build.make CMakeFiles/tree-sitter-java.dir/build
.PHONY : tree-sitter-java/fast

#=============================================================================
# Target rules for targets named tree-sitter-c

# Build rule for target.
tree-sitter-c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-c
.PHONY : tree-sitter-c

# fast build rule for target.
tree-sitter-c/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c.dir/build.make CMakeFiles/tree-sitter-c.dir/build
.PHONY : tree-sitter-c/fast

#=============================================================================
# Target rules for targets named CodeWizard

# Build rule for target.
CodeWizard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CodeWizard
.PHONY : CodeWizard

# fast build rule for target.
CodeWizard/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/build
.PHONY : CodeWizard/fast

#=============================================================================
# Target rules for targets named tree-sitter-cpp_autogen

# Build rule for target.
tree-sitter-cpp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-cpp_autogen
.PHONY : tree-sitter-cpp_autogen

# fast build rule for target.
tree-sitter-cpp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-cpp_autogen.dir/build.make CMakeFiles/tree-sitter-cpp_autogen.dir/build
.PHONY : tree-sitter-cpp_autogen/fast

#=============================================================================
# Target rules for targets named tree-sitter-c-sharp_autogen

# Build rule for target.
tree-sitter-c-sharp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-c-sharp_autogen
.PHONY : tree-sitter-c-sharp_autogen

# fast build rule for target.
tree-sitter-c-sharp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c-sharp_autogen.dir/build.make CMakeFiles/tree-sitter-c-sharp_autogen.dir/build
.PHONY : tree-sitter-c-sharp_autogen/fast

#=============================================================================
# Target rules for targets named tree-sitter-python_autogen

# Build rule for target.
tree-sitter-python_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-python_autogen
.PHONY : tree-sitter-python_autogen

# fast build rule for target.
tree-sitter-python_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-python_autogen.dir/build.make CMakeFiles/tree-sitter-python_autogen.dir/build
.PHONY : tree-sitter-python_autogen/fast

#=============================================================================
# Target rules for targets named tree-sitter-rust_autogen

# Build rule for target.
tree-sitter-rust_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-rust_autogen
.PHONY : tree-sitter-rust_autogen

# fast build rule for target.
tree-sitter-rust_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-rust_autogen.dir/build.make CMakeFiles/tree-sitter-rust_autogen.dir/build
.PHONY : tree-sitter-rust_autogen/fast

#=============================================================================
# Target rules for targets named tree-sitter-javascript_autogen

# Build rule for target.
tree-sitter-javascript_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-javascript_autogen
.PHONY : tree-sitter-javascript_autogen

# fast build rule for target.
tree-sitter-javascript_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-javascript_autogen.dir/build.make CMakeFiles/tree-sitter-javascript_autogen.dir/build
.PHONY : tree-sitter-javascript_autogen/fast

#=============================================================================
# Target rules for targets named tree-sitter-typescript_autogen

# Build rule for target.
tree-sitter-typescript_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-typescript_autogen
.PHONY : tree-sitter-typescript_autogen

# fast build rule for target.
tree-sitter-typescript_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-typescript_autogen.dir/build.make CMakeFiles/tree-sitter-typescript_autogen.dir/build
.PHONY : tree-sitter-typescript_autogen/fast

#=============================================================================
# Target rules for targets named tree-sitter-html_autogen

# Build rule for target.
tree-sitter-html_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-html_autogen
.PHONY : tree-sitter-html_autogen

# fast build rule for target.
tree-sitter-html_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-html_autogen.dir/build.make CMakeFiles/tree-sitter-html_autogen.dir/build
.PHONY : tree-sitter-html_autogen/fast

#=============================================================================
# Target rules for targets named tree-sitter-lua_autogen

# Build rule for target.
tree-sitter-lua_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-lua_autogen
.PHONY : tree-sitter-lua_autogen

# fast build rule for target.
tree-sitter-lua_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-lua_autogen.dir/build.make CMakeFiles/tree-sitter-lua_autogen.dir/build
.PHONY : tree-sitter-lua_autogen/fast

#=============================================================================
# Target rules for targets named tree-sitter-glsl_autogen

# Build rule for target.
tree-sitter-glsl_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-glsl_autogen
.PHONY : tree-sitter-glsl_autogen

# fast build rule for target.
tree-sitter-glsl_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-glsl_autogen.dir/build.make CMakeFiles/tree-sitter-glsl_autogen.dir/build
.PHONY : tree-sitter-glsl_autogen/fast

#=============================================================================
# Target rules for targets named tree-sitter-wgsl_autogen

# Build rule for target.
tree-sitter-wgsl_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-wgsl_autogen
.PHONY : tree-sitter-wgsl_autogen

# fast build rule for target.
tree-sitter-wgsl_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-wgsl_autogen.dir/build.make CMakeFiles/tree-sitter-wgsl_autogen.dir/build
.PHONY : tree-sitter-wgsl_autogen/fast

#=============================================================================
# Target rules for targets named tree-sitter-go_autogen

# Build rule for target.
tree-sitter-go_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-go_autogen
.PHONY : tree-sitter-go_autogen

# fast build rule for target.
tree-sitter-go_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-go_autogen.dir/build.make CMakeFiles/tree-sitter-go_autogen.dir/build
.PHONY : tree-sitter-go_autogen/fast

#=============================================================================
# Target rules for targets named tree-sitter-java_autogen

# Build rule for target.
tree-sitter-java_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-java_autogen
.PHONY : tree-sitter-java_autogen

# fast build rule for target.
tree-sitter-java_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-java_autogen.dir/build.make CMakeFiles/tree-sitter-java_autogen.dir/build
.PHONY : tree-sitter-java_autogen/fast

#=============================================================================
# Target rules for targets named tree-sitter-c_autogen

# Build rule for target.
tree-sitter-c_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter-c_autogen
.PHONY : tree-sitter-c_autogen

# fast build rule for target.
tree-sitter-c_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c_autogen.dir/build.make CMakeFiles/tree-sitter-c_autogen.dir/build
.PHONY : tree-sitter-c_autogen/fast

#=============================================================================
# Target rules for targets named CodeWizard_autogen

# Build rule for target.
CodeWizard_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CodeWizard_autogen
.PHONY : CodeWizard_autogen

# fast build rule for target.
CodeWizard_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard_autogen.dir/build.make CMakeFiles/CodeWizard_autogen.dir/build
.PHONY : CodeWizard_autogen/fast

#=============================================================================
# Target rules for targets named tree-sitter

# Build rule for target.
tree-sitter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter
.PHONY : tree-sitter

# fast build rule for target.
tree-sitter/fast:
	$(MAKE) $(MAKESILENT) -f extern/tree-sitter/CMakeFiles/tree-sitter.dir/build.make extern/tree-sitter/CMakeFiles/tree-sitter.dir/build
.PHONY : tree-sitter/fast

#=============================================================================
# Target rules for targets named tree-sitter_autogen

# Build rule for target.
tree-sitter_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree-sitter_autogen
.PHONY : tree-sitter_autogen

# fast build rule for target.
tree-sitter_autogen/fast:
	$(MAKE) $(MAKESILENT) -f extern/tree-sitter/CMakeFiles/tree-sitter_autogen.dir/build.make extern/tree-sitter/CMakeFiles/tree-sitter_autogen.dir/build
.PHONY : tree-sitter_autogen/fast

CodeWizard_autogen/mocs_compilation.o: CodeWizard_autogen/mocs_compilation.cpp.o
.PHONY : CodeWizard_autogen/mocs_compilation.o

# target to build an object file
CodeWizard_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/CodeWizard_autogen/mocs_compilation.cpp.o
.PHONY : CodeWizard_autogen/mocs_compilation.cpp.o

CodeWizard_autogen/mocs_compilation.i: CodeWizard_autogen/mocs_compilation.cpp.i
.PHONY : CodeWizard_autogen/mocs_compilation.i

# target to preprocess a source file
CodeWizard_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/CodeWizard_autogen/mocs_compilation.cpp.i
.PHONY : CodeWizard_autogen/mocs_compilation.cpp.i

CodeWizard_autogen/mocs_compilation.s: CodeWizard_autogen/mocs_compilation.cpp.s
.PHONY : CodeWizard_autogen/mocs_compilation.s

# target to generate assembly for a file
CodeWizard_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/CodeWizard_autogen/mocs_compilation.cpp.s
.PHONY : CodeWizard_autogen/mocs_compilation.cpp.s

extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.o: extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c-sharp.dir/build.make CMakeFiles/tree-sitter-c-sharp.dir/extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.c.o

extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.i: extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c-sharp.dir/build.make CMakeFiles/tree-sitter-c-sharp.dir/extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.c.i

extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.s: extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c-sharp.dir/build.make CMakeFiles/tree-sitter-c-sharp.dir/extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.c.s

extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.o: extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c-sharp.dir/build.make CMakeFiles/tree-sitter-c-sharp.dir/extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.c.o

extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.i: extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c-sharp.dir/build.make CMakeFiles/tree-sitter-c-sharp.dir/extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.c.i

extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.s: extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c-sharp.dir/build.make CMakeFiles/tree-sitter-c-sharp.dir/extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.c.s

extern/tree-sitter-parsers/tree-sitter-c/src/parser.o: extern/tree-sitter-parsers/tree-sitter-c/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-c/src/parser.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-c/src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c.dir/build.make CMakeFiles/tree-sitter-c.dir/extern/tree-sitter-parsers/tree-sitter-c/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-c/src/parser.c.o

extern/tree-sitter-parsers/tree-sitter-c/src/parser.i: extern/tree-sitter-parsers/tree-sitter-c/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-c/src/parser.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-c/src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c.dir/build.make CMakeFiles/tree-sitter-c.dir/extern/tree-sitter-parsers/tree-sitter-c/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-c/src/parser.c.i

extern/tree-sitter-parsers/tree-sitter-c/src/parser.s: extern/tree-sitter-parsers/tree-sitter-c/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-c/src/parser.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-c/src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c.dir/build.make CMakeFiles/tree-sitter-c.dir/extern/tree-sitter-parsers/tree-sitter-c/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-c/src/parser.c.s

extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.o: extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-cpp.dir/build.make CMakeFiles/tree-sitter-cpp.dir/extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.c.o

extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.i: extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-cpp.dir/build.make CMakeFiles/tree-sitter-cpp.dir/extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.c.i

extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.s: extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-cpp.dir/build.make CMakeFiles/tree-sitter-cpp.dir/extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.c.s

extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.o: extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-cpp.dir/build.make CMakeFiles/tree-sitter-cpp.dir/extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.c.o

extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.i: extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-cpp.dir/build.make CMakeFiles/tree-sitter-cpp.dir/extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.c.i

extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.s: extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-cpp.dir/build.make CMakeFiles/tree-sitter-cpp.dir/extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.c.s

extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.o: extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-glsl.dir/build.make CMakeFiles/tree-sitter-glsl.dir/extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.c.o

extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.i: extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-glsl.dir/build.make CMakeFiles/tree-sitter-glsl.dir/extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.c.i

extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.s: extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-glsl.dir/build.make CMakeFiles/tree-sitter-glsl.dir/extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.c.s

extern/tree-sitter-parsers/tree-sitter-go/src/parser.o: extern/tree-sitter-parsers/tree-sitter-go/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-go/src/parser.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-go/src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-go.dir/build.make CMakeFiles/tree-sitter-go.dir/extern/tree-sitter-parsers/tree-sitter-go/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-go/src/parser.c.o

extern/tree-sitter-parsers/tree-sitter-go/src/parser.i: extern/tree-sitter-parsers/tree-sitter-go/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-go/src/parser.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-go/src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-go.dir/build.make CMakeFiles/tree-sitter-go.dir/extern/tree-sitter-parsers/tree-sitter-go/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-go/src/parser.c.i

extern/tree-sitter-parsers/tree-sitter-go/src/parser.s: extern/tree-sitter-parsers/tree-sitter-go/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-go/src/parser.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-go/src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-go.dir/build.make CMakeFiles/tree-sitter-go.dir/extern/tree-sitter-parsers/tree-sitter-go/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-go/src/parser.c.s

extern/tree-sitter-parsers/tree-sitter-html/src/parser.o: extern/tree-sitter-parsers/tree-sitter-html/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-html/src/parser.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-html/src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-html.dir/build.make CMakeFiles/tree-sitter-html.dir/extern/tree-sitter-parsers/tree-sitter-html/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-html/src/parser.c.o

extern/tree-sitter-parsers/tree-sitter-html/src/parser.i: extern/tree-sitter-parsers/tree-sitter-html/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-html/src/parser.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-html/src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-html.dir/build.make CMakeFiles/tree-sitter-html.dir/extern/tree-sitter-parsers/tree-sitter-html/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-html/src/parser.c.i

extern/tree-sitter-parsers/tree-sitter-html/src/parser.s: extern/tree-sitter-parsers/tree-sitter-html/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-html/src/parser.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-html/src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-html.dir/build.make CMakeFiles/tree-sitter-html.dir/extern/tree-sitter-parsers/tree-sitter-html/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-html/src/parser.c.s

extern/tree-sitter-parsers/tree-sitter-html/src/scanner.o: extern/tree-sitter-parsers/tree-sitter-html/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-html/src/scanner.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-html/src/scanner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-html.dir/build.make CMakeFiles/tree-sitter-html.dir/extern/tree-sitter-parsers/tree-sitter-html/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-html/src/scanner.c.o

extern/tree-sitter-parsers/tree-sitter-html/src/scanner.i: extern/tree-sitter-parsers/tree-sitter-html/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-html/src/scanner.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-html/src/scanner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-html.dir/build.make CMakeFiles/tree-sitter-html.dir/extern/tree-sitter-parsers/tree-sitter-html/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-html/src/scanner.c.i

extern/tree-sitter-parsers/tree-sitter-html/src/scanner.s: extern/tree-sitter-parsers/tree-sitter-html/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-html/src/scanner.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-html/src/scanner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-html.dir/build.make CMakeFiles/tree-sitter-html.dir/extern/tree-sitter-parsers/tree-sitter-html/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-html/src/scanner.c.s

extern/tree-sitter-parsers/tree-sitter-java/src/parser.o: extern/tree-sitter-parsers/tree-sitter-java/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-java/src/parser.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-java/src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-java.dir/build.make CMakeFiles/tree-sitter-java.dir/extern/tree-sitter-parsers/tree-sitter-java/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-java/src/parser.c.o

extern/tree-sitter-parsers/tree-sitter-java/src/parser.i: extern/tree-sitter-parsers/tree-sitter-java/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-java/src/parser.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-java/src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-java.dir/build.make CMakeFiles/tree-sitter-java.dir/extern/tree-sitter-parsers/tree-sitter-java/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-java/src/parser.c.i

extern/tree-sitter-parsers/tree-sitter-java/src/parser.s: extern/tree-sitter-parsers/tree-sitter-java/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-java/src/parser.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-java/src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-java.dir/build.make CMakeFiles/tree-sitter-java.dir/extern/tree-sitter-parsers/tree-sitter-java/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-java/src/parser.c.s

extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.o: extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-javascript.dir/build.make CMakeFiles/tree-sitter-javascript.dir/extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.c.o

extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.i: extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-javascript.dir/build.make CMakeFiles/tree-sitter-javascript.dir/extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.c.i

extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.s: extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-javascript.dir/build.make CMakeFiles/tree-sitter-javascript.dir/extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.c.s

extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.o: extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-javascript.dir/build.make CMakeFiles/tree-sitter-javascript.dir/extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.c.o

extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.i: extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-javascript.dir/build.make CMakeFiles/tree-sitter-javascript.dir/extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.c.i

extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.s: extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-javascript.dir/build.make CMakeFiles/tree-sitter-javascript.dir/extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.c.s

extern/tree-sitter-parsers/tree-sitter-lua/src/parser.o: extern/tree-sitter-parsers/tree-sitter-lua/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-lua/src/parser.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-lua/src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-lua.dir/build.make CMakeFiles/tree-sitter-lua.dir/extern/tree-sitter-parsers/tree-sitter-lua/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-lua/src/parser.c.o

extern/tree-sitter-parsers/tree-sitter-lua/src/parser.i: extern/tree-sitter-parsers/tree-sitter-lua/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-lua/src/parser.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-lua/src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-lua.dir/build.make CMakeFiles/tree-sitter-lua.dir/extern/tree-sitter-parsers/tree-sitter-lua/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-lua/src/parser.c.i

extern/tree-sitter-parsers/tree-sitter-lua/src/parser.s: extern/tree-sitter-parsers/tree-sitter-lua/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-lua/src/parser.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-lua/src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-lua.dir/build.make CMakeFiles/tree-sitter-lua.dir/extern/tree-sitter-parsers/tree-sitter-lua/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-lua/src/parser.c.s

extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.o: extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-lua.dir/build.make CMakeFiles/tree-sitter-lua.dir/extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.c.o

extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.i: extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-lua.dir/build.make CMakeFiles/tree-sitter-lua.dir/extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.c.i

extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.s: extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-lua.dir/build.make CMakeFiles/tree-sitter-lua.dir/extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.c.s

extern/tree-sitter-parsers/tree-sitter-python/src/parser.o: extern/tree-sitter-parsers/tree-sitter-python/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-python/src/parser.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-python/src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-python.dir/build.make CMakeFiles/tree-sitter-python.dir/extern/tree-sitter-parsers/tree-sitter-python/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-python/src/parser.c.o

extern/tree-sitter-parsers/tree-sitter-python/src/parser.i: extern/tree-sitter-parsers/tree-sitter-python/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-python/src/parser.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-python/src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-python.dir/build.make CMakeFiles/tree-sitter-python.dir/extern/tree-sitter-parsers/tree-sitter-python/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-python/src/parser.c.i

extern/tree-sitter-parsers/tree-sitter-python/src/parser.s: extern/tree-sitter-parsers/tree-sitter-python/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-python/src/parser.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-python/src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-python.dir/build.make CMakeFiles/tree-sitter-python.dir/extern/tree-sitter-parsers/tree-sitter-python/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-python/src/parser.c.s

extern/tree-sitter-parsers/tree-sitter-python/src/scanner.o: extern/tree-sitter-parsers/tree-sitter-python/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-python/src/scanner.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-python/src/scanner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-python.dir/build.make CMakeFiles/tree-sitter-python.dir/extern/tree-sitter-parsers/tree-sitter-python/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-python/src/scanner.c.o

extern/tree-sitter-parsers/tree-sitter-python/src/scanner.i: extern/tree-sitter-parsers/tree-sitter-python/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-python/src/scanner.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-python/src/scanner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-python.dir/build.make CMakeFiles/tree-sitter-python.dir/extern/tree-sitter-parsers/tree-sitter-python/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-python/src/scanner.c.i

extern/tree-sitter-parsers/tree-sitter-python/src/scanner.s: extern/tree-sitter-parsers/tree-sitter-python/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-python/src/scanner.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-python/src/scanner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-python.dir/build.make CMakeFiles/tree-sitter-python.dir/extern/tree-sitter-parsers/tree-sitter-python/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-python/src/scanner.c.s

extern/tree-sitter-parsers/tree-sitter-rust/src/parser.o: extern/tree-sitter-parsers/tree-sitter-rust/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-rust/src/parser.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-rust/src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-rust.dir/build.make CMakeFiles/tree-sitter-rust.dir/extern/tree-sitter-parsers/tree-sitter-rust/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-rust/src/parser.c.o

extern/tree-sitter-parsers/tree-sitter-rust/src/parser.i: extern/tree-sitter-parsers/tree-sitter-rust/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-rust/src/parser.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-rust/src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-rust.dir/build.make CMakeFiles/tree-sitter-rust.dir/extern/tree-sitter-parsers/tree-sitter-rust/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-rust/src/parser.c.i

extern/tree-sitter-parsers/tree-sitter-rust/src/parser.s: extern/tree-sitter-parsers/tree-sitter-rust/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-rust/src/parser.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-rust/src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-rust.dir/build.make CMakeFiles/tree-sitter-rust.dir/extern/tree-sitter-parsers/tree-sitter-rust/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-rust/src/parser.c.s

extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.o: extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-rust.dir/build.make CMakeFiles/tree-sitter-rust.dir/extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.c.o

extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.i: extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-rust.dir/build.make CMakeFiles/tree-sitter-rust.dir/extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.c.i

extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.s: extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-rust.dir/build.make CMakeFiles/tree-sitter-rust.dir/extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.c.s

extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.o: extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-typescript.dir/build.make CMakeFiles/tree-sitter-typescript.dir/extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.c.o

extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.i: extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-typescript.dir/build.make CMakeFiles/tree-sitter-typescript.dir/extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.c.i

extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.s: extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-typescript.dir/build.make CMakeFiles/tree-sitter-typescript.dir/extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.c.s

extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.o: extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-typescript.dir/build.make CMakeFiles/tree-sitter-typescript.dir/extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.c.o

extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.i: extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-typescript.dir/build.make CMakeFiles/tree-sitter-typescript.dir/extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.c.i

extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.s: extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-typescript.dir/build.make CMakeFiles/tree-sitter-typescript.dir/extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.c.s

extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.o: extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-wgsl.dir/build.make CMakeFiles/tree-sitter-wgsl.dir/extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.c.o

extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.i: extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-wgsl.dir/build.make CMakeFiles/tree-sitter-wgsl.dir/extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.c.i

extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.s: extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-wgsl.dir/build.make CMakeFiles/tree-sitter-wgsl.dir/extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.c.s

extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.o: extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.o

# target to build an object file
extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-wgsl.dir/build.make CMakeFiles/tree-sitter-wgsl.dir/extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.c.o
.PHONY : extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.c.o

extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.i: extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.i

# target to preprocess a source file
extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-wgsl.dir/build.make CMakeFiles/tree-sitter-wgsl.dir/extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.c.i
.PHONY : extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.c.i

extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.s: extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.s

# target to generate assembly for a file
extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-wgsl.dir/build.make CMakeFiles/tree-sitter-wgsl.dir/extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.c.s
.PHONY : extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.c.s

language.o: language.cpp.o
.PHONY : language.o

# target to build an object file
language.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/language.cpp.o
.PHONY : language.cpp.o

language.i: language.cpp.i
.PHONY : language.i

# target to preprocess a source file
language.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/language.cpp.i
.PHONY : language.cpp.i

language.s: language.cpp.s
.PHONY : language.s

# target to generate assembly for a file
language.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/language.cpp.s
.PHONY : language.cpp.s

languageserverclient.o: languageserverclient.cpp.o
.PHONY : languageserverclient.o

# target to build an object file
languageserverclient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/languageserverclient.cpp.o
.PHONY : languageserverclient.cpp.o

languageserverclient.i: languageserverclient.cpp.i
.PHONY : languageserverclient.i

# target to preprocess a source file
languageserverclient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/languageserverclient.cpp.i
.PHONY : languageserverclient.cpp.i

languageserverclient.s: languageserverclient.cpp.s
.PHONY : languageserverclient.s

# target to generate assembly for a file
languageserverclient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/languageserverclient.cpp.s
.PHONY : languageserverclient.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

mytextedit.o: mytextedit.cpp.o
.PHONY : mytextedit.o

# target to build an object file
mytextedit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/mytextedit.cpp.o
.PHONY : mytextedit.cpp.o

mytextedit.i: mytextedit.cpp.i
.PHONY : mytextedit.i

# target to preprocess a source file
mytextedit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/mytextedit.cpp.i
.PHONY : mytextedit.cpp.i

mytextedit.s: mytextedit.cpp.s
.PHONY : mytextedit.s

# target to generate assembly for a file
mytextedit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/mytextedit.cpp.s
.PHONY : mytextedit.cpp.s

recordinglight.o: recordinglight.cpp.o
.PHONY : recordinglight.o

# target to build an object file
recordinglight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/recordinglight.cpp.o
.PHONY : recordinglight.cpp.o

recordinglight.i: recordinglight.cpp.i
.PHONY : recordinglight.i

# target to preprocess a source file
recordinglight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/recordinglight.cpp.i
.PHONY : recordinglight.cpp.i

recordinglight.s: recordinglight.cpp.s
.PHONY : recordinglight.s

# target to generate assembly for a file
recordinglight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/recordinglight.cpp.s
.PHONY : recordinglight.cpp.s

syntaxhighlighter.o: syntaxhighlighter.cpp.o
.PHONY : syntaxhighlighter.o

# target to build an object file
syntaxhighlighter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/syntaxhighlighter.cpp.o
.PHONY : syntaxhighlighter.cpp.o

syntaxhighlighter.i: syntaxhighlighter.cpp.i
.PHONY : syntaxhighlighter.i

# target to preprocess a source file
syntaxhighlighter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/syntaxhighlighter.cpp.i
.PHONY : syntaxhighlighter.cpp.i

syntaxhighlighter.s: syntaxhighlighter.cpp.s
.PHONY : syntaxhighlighter.s

# target to generate assembly for a file
syntaxhighlighter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CodeWizard.dir/build.make CMakeFiles/CodeWizard.dir/syntaxhighlighter.cpp.s
.PHONY : syntaxhighlighter.cpp.s

tree-sitter-c-sharp_autogen/mocs_compilation.o: tree-sitter-c-sharp_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-c-sharp_autogen/mocs_compilation.o

# target to build an object file
tree-sitter-c-sharp_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c-sharp.dir/build.make CMakeFiles/tree-sitter-c-sharp.dir/tree-sitter-c-sharp_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-c-sharp_autogen/mocs_compilation.cpp.o

tree-sitter-c-sharp_autogen/mocs_compilation.i: tree-sitter-c-sharp_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-c-sharp_autogen/mocs_compilation.i

# target to preprocess a source file
tree-sitter-c-sharp_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c-sharp.dir/build.make CMakeFiles/tree-sitter-c-sharp.dir/tree-sitter-c-sharp_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-c-sharp_autogen/mocs_compilation.cpp.i

tree-sitter-c-sharp_autogen/mocs_compilation.s: tree-sitter-c-sharp_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-c-sharp_autogen/mocs_compilation.s

# target to generate assembly for a file
tree-sitter-c-sharp_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c-sharp.dir/build.make CMakeFiles/tree-sitter-c-sharp.dir/tree-sitter-c-sharp_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-c-sharp_autogen/mocs_compilation.cpp.s

tree-sitter-c_autogen/mocs_compilation.o: tree-sitter-c_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-c_autogen/mocs_compilation.o

# target to build an object file
tree-sitter-c_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c.dir/build.make CMakeFiles/tree-sitter-c.dir/tree-sitter-c_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-c_autogen/mocs_compilation.cpp.o

tree-sitter-c_autogen/mocs_compilation.i: tree-sitter-c_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-c_autogen/mocs_compilation.i

# target to preprocess a source file
tree-sitter-c_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c.dir/build.make CMakeFiles/tree-sitter-c.dir/tree-sitter-c_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-c_autogen/mocs_compilation.cpp.i

tree-sitter-c_autogen/mocs_compilation.s: tree-sitter-c_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-c_autogen/mocs_compilation.s

# target to generate assembly for a file
tree-sitter-c_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-c.dir/build.make CMakeFiles/tree-sitter-c.dir/tree-sitter-c_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-c_autogen/mocs_compilation.cpp.s

tree-sitter-cpp_autogen/mocs_compilation.o: tree-sitter-cpp_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-cpp_autogen/mocs_compilation.o

# target to build an object file
tree-sitter-cpp_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-cpp.dir/build.make CMakeFiles/tree-sitter-cpp.dir/tree-sitter-cpp_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-cpp_autogen/mocs_compilation.cpp.o

tree-sitter-cpp_autogen/mocs_compilation.i: tree-sitter-cpp_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-cpp_autogen/mocs_compilation.i

# target to preprocess a source file
tree-sitter-cpp_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-cpp.dir/build.make CMakeFiles/tree-sitter-cpp.dir/tree-sitter-cpp_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-cpp_autogen/mocs_compilation.cpp.i

tree-sitter-cpp_autogen/mocs_compilation.s: tree-sitter-cpp_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-cpp_autogen/mocs_compilation.s

# target to generate assembly for a file
tree-sitter-cpp_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-cpp.dir/build.make CMakeFiles/tree-sitter-cpp.dir/tree-sitter-cpp_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-cpp_autogen/mocs_compilation.cpp.s

tree-sitter-glsl_autogen/mocs_compilation.o: tree-sitter-glsl_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-glsl_autogen/mocs_compilation.o

# target to build an object file
tree-sitter-glsl_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-glsl.dir/build.make CMakeFiles/tree-sitter-glsl.dir/tree-sitter-glsl_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-glsl_autogen/mocs_compilation.cpp.o

tree-sitter-glsl_autogen/mocs_compilation.i: tree-sitter-glsl_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-glsl_autogen/mocs_compilation.i

# target to preprocess a source file
tree-sitter-glsl_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-glsl.dir/build.make CMakeFiles/tree-sitter-glsl.dir/tree-sitter-glsl_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-glsl_autogen/mocs_compilation.cpp.i

tree-sitter-glsl_autogen/mocs_compilation.s: tree-sitter-glsl_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-glsl_autogen/mocs_compilation.s

# target to generate assembly for a file
tree-sitter-glsl_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-glsl.dir/build.make CMakeFiles/tree-sitter-glsl.dir/tree-sitter-glsl_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-glsl_autogen/mocs_compilation.cpp.s

tree-sitter-go_autogen/mocs_compilation.o: tree-sitter-go_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-go_autogen/mocs_compilation.o

# target to build an object file
tree-sitter-go_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-go.dir/build.make CMakeFiles/tree-sitter-go.dir/tree-sitter-go_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-go_autogen/mocs_compilation.cpp.o

tree-sitter-go_autogen/mocs_compilation.i: tree-sitter-go_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-go_autogen/mocs_compilation.i

# target to preprocess a source file
tree-sitter-go_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-go.dir/build.make CMakeFiles/tree-sitter-go.dir/tree-sitter-go_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-go_autogen/mocs_compilation.cpp.i

tree-sitter-go_autogen/mocs_compilation.s: tree-sitter-go_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-go_autogen/mocs_compilation.s

# target to generate assembly for a file
tree-sitter-go_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-go.dir/build.make CMakeFiles/tree-sitter-go.dir/tree-sitter-go_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-go_autogen/mocs_compilation.cpp.s

tree-sitter-html_autogen/mocs_compilation.o: tree-sitter-html_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-html_autogen/mocs_compilation.o

# target to build an object file
tree-sitter-html_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-html.dir/build.make CMakeFiles/tree-sitter-html.dir/tree-sitter-html_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-html_autogen/mocs_compilation.cpp.o

tree-sitter-html_autogen/mocs_compilation.i: tree-sitter-html_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-html_autogen/mocs_compilation.i

# target to preprocess a source file
tree-sitter-html_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-html.dir/build.make CMakeFiles/tree-sitter-html.dir/tree-sitter-html_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-html_autogen/mocs_compilation.cpp.i

tree-sitter-html_autogen/mocs_compilation.s: tree-sitter-html_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-html_autogen/mocs_compilation.s

# target to generate assembly for a file
tree-sitter-html_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-html.dir/build.make CMakeFiles/tree-sitter-html.dir/tree-sitter-html_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-html_autogen/mocs_compilation.cpp.s

tree-sitter-java_autogen/mocs_compilation.o: tree-sitter-java_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-java_autogen/mocs_compilation.o

# target to build an object file
tree-sitter-java_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-java.dir/build.make CMakeFiles/tree-sitter-java.dir/tree-sitter-java_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-java_autogen/mocs_compilation.cpp.o

tree-sitter-java_autogen/mocs_compilation.i: tree-sitter-java_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-java_autogen/mocs_compilation.i

# target to preprocess a source file
tree-sitter-java_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-java.dir/build.make CMakeFiles/tree-sitter-java.dir/tree-sitter-java_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-java_autogen/mocs_compilation.cpp.i

tree-sitter-java_autogen/mocs_compilation.s: tree-sitter-java_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-java_autogen/mocs_compilation.s

# target to generate assembly for a file
tree-sitter-java_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-java.dir/build.make CMakeFiles/tree-sitter-java.dir/tree-sitter-java_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-java_autogen/mocs_compilation.cpp.s

tree-sitter-javascript_autogen/mocs_compilation.o: tree-sitter-javascript_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-javascript_autogen/mocs_compilation.o

# target to build an object file
tree-sitter-javascript_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-javascript.dir/build.make CMakeFiles/tree-sitter-javascript.dir/tree-sitter-javascript_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-javascript_autogen/mocs_compilation.cpp.o

tree-sitter-javascript_autogen/mocs_compilation.i: tree-sitter-javascript_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-javascript_autogen/mocs_compilation.i

# target to preprocess a source file
tree-sitter-javascript_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-javascript.dir/build.make CMakeFiles/tree-sitter-javascript.dir/tree-sitter-javascript_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-javascript_autogen/mocs_compilation.cpp.i

tree-sitter-javascript_autogen/mocs_compilation.s: tree-sitter-javascript_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-javascript_autogen/mocs_compilation.s

# target to generate assembly for a file
tree-sitter-javascript_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-javascript.dir/build.make CMakeFiles/tree-sitter-javascript.dir/tree-sitter-javascript_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-javascript_autogen/mocs_compilation.cpp.s

tree-sitter-lua_autogen/mocs_compilation.o: tree-sitter-lua_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-lua_autogen/mocs_compilation.o

# target to build an object file
tree-sitter-lua_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-lua.dir/build.make CMakeFiles/tree-sitter-lua.dir/tree-sitter-lua_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-lua_autogen/mocs_compilation.cpp.o

tree-sitter-lua_autogen/mocs_compilation.i: tree-sitter-lua_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-lua_autogen/mocs_compilation.i

# target to preprocess a source file
tree-sitter-lua_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-lua.dir/build.make CMakeFiles/tree-sitter-lua.dir/tree-sitter-lua_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-lua_autogen/mocs_compilation.cpp.i

tree-sitter-lua_autogen/mocs_compilation.s: tree-sitter-lua_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-lua_autogen/mocs_compilation.s

# target to generate assembly for a file
tree-sitter-lua_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-lua.dir/build.make CMakeFiles/tree-sitter-lua.dir/tree-sitter-lua_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-lua_autogen/mocs_compilation.cpp.s

tree-sitter-python_autogen/mocs_compilation.o: tree-sitter-python_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-python_autogen/mocs_compilation.o

# target to build an object file
tree-sitter-python_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-python.dir/build.make CMakeFiles/tree-sitter-python.dir/tree-sitter-python_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-python_autogen/mocs_compilation.cpp.o

tree-sitter-python_autogen/mocs_compilation.i: tree-sitter-python_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-python_autogen/mocs_compilation.i

# target to preprocess a source file
tree-sitter-python_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-python.dir/build.make CMakeFiles/tree-sitter-python.dir/tree-sitter-python_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-python_autogen/mocs_compilation.cpp.i

tree-sitter-python_autogen/mocs_compilation.s: tree-sitter-python_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-python_autogen/mocs_compilation.s

# target to generate assembly for a file
tree-sitter-python_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-python.dir/build.make CMakeFiles/tree-sitter-python.dir/tree-sitter-python_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-python_autogen/mocs_compilation.cpp.s

tree-sitter-rust_autogen/mocs_compilation.o: tree-sitter-rust_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-rust_autogen/mocs_compilation.o

# target to build an object file
tree-sitter-rust_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-rust.dir/build.make CMakeFiles/tree-sitter-rust.dir/tree-sitter-rust_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-rust_autogen/mocs_compilation.cpp.o

tree-sitter-rust_autogen/mocs_compilation.i: tree-sitter-rust_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-rust_autogen/mocs_compilation.i

# target to preprocess a source file
tree-sitter-rust_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-rust.dir/build.make CMakeFiles/tree-sitter-rust.dir/tree-sitter-rust_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-rust_autogen/mocs_compilation.cpp.i

tree-sitter-rust_autogen/mocs_compilation.s: tree-sitter-rust_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-rust_autogen/mocs_compilation.s

# target to generate assembly for a file
tree-sitter-rust_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-rust.dir/build.make CMakeFiles/tree-sitter-rust.dir/tree-sitter-rust_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-rust_autogen/mocs_compilation.cpp.s

tree-sitter-typescript_autogen/mocs_compilation.o: tree-sitter-typescript_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-typescript_autogen/mocs_compilation.o

# target to build an object file
tree-sitter-typescript_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-typescript.dir/build.make CMakeFiles/tree-sitter-typescript.dir/tree-sitter-typescript_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-typescript_autogen/mocs_compilation.cpp.o

tree-sitter-typescript_autogen/mocs_compilation.i: tree-sitter-typescript_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-typescript_autogen/mocs_compilation.i

# target to preprocess a source file
tree-sitter-typescript_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-typescript.dir/build.make CMakeFiles/tree-sitter-typescript.dir/tree-sitter-typescript_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-typescript_autogen/mocs_compilation.cpp.i

tree-sitter-typescript_autogen/mocs_compilation.s: tree-sitter-typescript_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-typescript_autogen/mocs_compilation.s

# target to generate assembly for a file
tree-sitter-typescript_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-typescript.dir/build.make CMakeFiles/tree-sitter-typescript.dir/tree-sitter-typescript_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-typescript_autogen/mocs_compilation.cpp.s

tree-sitter-wgsl_autogen/mocs_compilation.o: tree-sitter-wgsl_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-wgsl_autogen/mocs_compilation.o

# target to build an object file
tree-sitter-wgsl_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-wgsl.dir/build.make CMakeFiles/tree-sitter-wgsl.dir/tree-sitter-wgsl_autogen/mocs_compilation.cpp.o
.PHONY : tree-sitter-wgsl_autogen/mocs_compilation.cpp.o

tree-sitter-wgsl_autogen/mocs_compilation.i: tree-sitter-wgsl_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-wgsl_autogen/mocs_compilation.i

# target to preprocess a source file
tree-sitter-wgsl_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-wgsl.dir/build.make CMakeFiles/tree-sitter-wgsl.dir/tree-sitter-wgsl_autogen/mocs_compilation.cpp.i
.PHONY : tree-sitter-wgsl_autogen/mocs_compilation.cpp.i

tree-sitter-wgsl_autogen/mocs_compilation.s: tree-sitter-wgsl_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-wgsl_autogen/mocs_compilation.s

# target to generate assembly for a file
tree-sitter-wgsl_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree-sitter-wgsl.dir/build.make CMakeFiles/tree-sitter-wgsl.dir/tree-sitter-wgsl_autogen/mocs_compilation.cpp.s
.PHONY : tree-sitter-wgsl_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... CodeWizard_autogen"
	@echo "... tree-sitter-c-sharp_autogen"
	@echo "... tree-sitter-c_autogen"
	@echo "... tree-sitter-cpp_autogen"
	@echo "... tree-sitter-glsl_autogen"
	@echo "... tree-sitter-go_autogen"
	@echo "... tree-sitter-html_autogen"
	@echo "... tree-sitter-java_autogen"
	@echo "... tree-sitter-javascript_autogen"
	@echo "... tree-sitter-lua_autogen"
	@echo "... tree-sitter-python_autogen"
	@echo "... tree-sitter-rust_autogen"
	@echo "... tree-sitter-typescript_autogen"
	@echo "... tree-sitter-wgsl_autogen"
	@echo "... tree-sitter_autogen"
	@echo "... CodeWizard"
	@echo "... tree-sitter"
	@echo "... tree-sitter-c"
	@echo "... tree-sitter-c-sharp"
	@echo "... tree-sitter-cpp"
	@echo "... tree-sitter-glsl"
	@echo "... tree-sitter-go"
	@echo "... tree-sitter-html"
	@echo "... tree-sitter-java"
	@echo "... tree-sitter-javascript"
	@echo "... tree-sitter-lua"
	@echo "... tree-sitter-python"
	@echo "... tree-sitter-rust"
	@echo "... tree-sitter-typescript"
	@echo "... tree-sitter-wgsl"
	@echo "... CodeWizard_autogen/mocs_compilation.o"
	@echo "... CodeWizard_autogen/mocs_compilation.i"
	@echo "... CodeWizard_autogen/mocs_compilation.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-c-sharp/src/parser.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-c-sharp/src/scanner.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-c/src/parser.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-c/src/parser.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-c/src/parser.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-cpp/src/parser.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-cpp/src/scanner.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-glsl/src/parser.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-go/src/parser.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-go/src/parser.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-go/src/parser.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-html/src/parser.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-html/src/parser.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-html/src/parser.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-html/src/scanner.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-html/src/scanner.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-html/src/scanner.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-java/src/parser.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-java/src/parser.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-java/src/parser.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-javascript/src/parser.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-javascript/src/scanner.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-lua/src/parser.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-lua/src/parser.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-lua/src/parser.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-lua/src/scanner.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-python/src/parser.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-python/src/parser.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-python/src/parser.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-python/src/scanner.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-python/src/scanner.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-python/src/scanner.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-rust/src/parser.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-rust/src/parser.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-rust/src/parser.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-rust/src/scanner.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/parser.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-typescript/typescript/src/scanner.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-wgsl/src/parser.s"
	@echo "... extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.o"
	@echo "... extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.i"
	@echo "... extern/tree-sitter-parsers/tree-sitter-wgsl/src/scanner.s"
	@echo "... language.o"
	@echo "... language.i"
	@echo "... language.s"
	@echo "... languageserverclient.o"
	@echo "... languageserverclient.i"
	@echo "... languageserverclient.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... mytextedit.o"
	@echo "... mytextedit.i"
	@echo "... mytextedit.s"
	@echo "... recordinglight.o"
	@echo "... recordinglight.i"
	@echo "... recordinglight.s"
	@echo "... syntaxhighlighter.o"
	@echo "... syntaxhighlighter.i"
	@echo "... syntaxhighlighter.s"
	@echo "... tree-sitter-c-sharp_autogen/mocs_compilation.o"
	@echo "... tree-sitter-c-sharp_autogen/mocs_compilation.i"
	@echo "... tree-sitter-c-sharp_autogen/mocs_compilation.s"
	@echo "... tree-sitter-c_autogen/mocs_compilation.o"
	@echo "... tree-sitter-c_autogen/mocs_compilation.i"
	@echo "... tree-sitter-c_autogen/mocs_compilation.s"
	@echo "... tree-sitter-cpp_autogen/mocs_compilation.o"
	@echo "... tree-sitter-cpp_autogen/mocs_compilation.i"
	@echo "... tree-sitter-cpp_autogen/mocs_compilation.s"
	@echo "... tree-sitter-glsl_autogen/mocs_compilation.o"
	@echo "... tree-sitter-glsl_autogen/mocs_compilation.i"
	@echo "... tree-sitter-glsl_autogen/mocs_compilation.s"
	@echo "... tree-sitter-go_autogen/mocs_compilation.o"
	@echo "... tree-sitter-go_autogen/mocs_compilation.i"
	@echo "... tree-sitter-go_autogen/mocs_compilation.s"
	@echo "... tree-sitter-html_autogen/mocs_compilation.o"
	@echo "... tree-sitter-html_autogen/mocs_compilation.i"
	@echo "... tree-sitter-html_autogen/mocs_compilation.s"
	@echo "... tree-sitter-java_autogen/mocs_compilation.o"
	@echo "... tree-sitter-java_autogen/mocs_compilation.i"
	@echo "... tree-sitter-java_autogen/mocs_compilation.s"
	@echo "... tree-sitter-javascript_autogen/mocs_compilation.o"
	@echo "... tree-sitter-javascript_autogen/mocs_compilation.i"
	@echo "... tree-sitter-javascript_autogen/mocs_compilation.s"
	@echo "... tree-sitter-lua_autogen/mocs_compilation.o"
	@echo "... tree-sitter-lua_autogen/mocs_compilation.i"
	@echo "... tree-sitter-lua_autogen/mocs_compilation.s"
	@echo "... tree-sitter-python_autogen/mocs_compilation.o"
	@echo "... tree-sitter-python_autogen/mocs_compilation.i"
	@echo "... tree-sitter-python_autogen/mocs_compilation.s"
	@echo "... tree-sitter-rust_autogen/mocs_compilation.o"
	@echo "... tree-sitter-rust_autogen/mocs_compilation.i"
	@echo "... tree-sitter-rust_autogen/mocs_compilation.s"
	@echo "... tree-sitter-typescript_autogen/mocs_compilation.o"
	@echo "... tree-sitter-typescript_autogen/mocs_compilation.i"
	@echo "... tree-sitter-typescript_autogen/mocs_compilation.s"
	@echo "... tree-sitter-wgsl_autogen/mocs_compilation.o"
	@echo "... tree-sitter-wgsl_autogen/mocs_compilation.i"
	@echo "... tree-sitter-wgsl_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

